Add annotations
TangoAgency/material-intro-screen pull request #71
Opened 2017-01-31 11:15 UTC by bezmian

Update gradle version
 * Add proper annotations for Res assets and variables
 * Add @CallSuper in needed places

2017-02-01 12:19 UTC, radzio requested changes

2017-02-01 12:19 UTC, radzio commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +    @CallSuper
probably we don't need it because **onCreate** has **@CallSuper** already.

2017-02-01 12:19 UTC, radzio commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
>       * Override to execute this method on finish intro activity
Better java doc pls do we really need to make this method abstract?

2017-02-01 12:39 UTC, radzio requested changes

2017-02-01 12:39 UTC, radzio commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +                messageButton.setTextColor(color(adapter.getItem(position).backgroundColor()));
color -> getColor

2017-02-02 11:08 UTC, bezmian commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +    @CallSuper
I checked in IntroActivity and without @CallSuper annotation, a developer isn't forced to call super.onCreate(), so I have added that in MaterialIntroActivity.

2017-02-02 11:08 UTC, bezmian commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +                messageButton.setTextColor(color(adapter.getItem(position).backgroundColor()));
Fixed in https://github.com/TangoAgency/material-intro-screen/pull/72

2017-02-03 11:18 UTC, radzio commented
LGTM!

2017-02-03 11:18 UTC, radzio approved these changes

2017-02-03 11:18 UTC, merged