Fix bug when orientation changes, the screen goes transparent
TangoAgency/material-intro-screen pull request #72
Opened 2017-01-31 12:16 UTC by bezmian

* Improve code quality by extracting code to methods

2017-02-01 12:21 UTC, radzio requested changes

2017-02-01 12:21 UTC, radzio commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +        return color(adapter.getItem(position).backgroundColor());
rename **color** to **getColor** because inside you are calling ContextCompat.getColor

2017-02-01 16:59 UTC, bezmian commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +        return color(adapter.getItem(position).backgroundColor());
name getColor isn't available as in API 23 Google add getColor method with same parameters. I have created getColorFromRes

2017-02-03 08:45 UTC, radzio requested changes

2017-02-03 08:45 UTC, radzio commented on material-intro-screen/src/main/java/agency/tango/materialintroscreen/MaterialIntroActivity.java
> +        return (Integer) argbEvaluator.evaluate(positionOffset, getBackgroundColor(position), getBackgroundColor(position + 1));
why Integer and not int?

2017-02-03 10:04 UTC, radzio commented
LGTM!

2017-02-03 10:04 UTC, merged