Add prefix mis_ for all attributes from attrs.xml
TangoAgency/material-intro-screen pull request #73
Opened 2017-01-31 12:37 UTC by bezmian

2017-01-31 13:31 UTC, radzio commented
Please add **resourcePrefix**

2017-02-01 12:27 UTC, radzio requested changes

2017-02-01 12:27 UTC, radzio commented on material-intro-screen/src/main/res/values/styles.xml
> +    <style name="mis_ColoredButton" parent="Widget.AppCompat.Button.Colored">
Are you sure that this is good practice?

2017-02-01 12:27 UTC, radzio commented on material-intro-screen/src/main/res/values/styles.xml
> +    <style name="mis_Theme.Intro" parent="Theme.AppCompat.NoActionBar">
Check next commpent.

2017-02-01 15:21 UTC, bezmian commented on material-intro-screen/src/main/res/values/styles.xml
> +    <style name="mis_Theme.Intro" parent="Theme.AppCompat.NoActionBar">
I need to add this as resourcePrefix from gradle forces me to do that.

2017-02-01 15:21 UTC, bezmian commented on material-intro-screen/src/main/res/values/styles.xml
> +    <style name="mis_ColoredButton" parent="Widget.AppCompat.Button.Colored">
I need to add this as resourcePrefix from gradle forces me to do that.

2017-02-03 10:41 UTC, radzio approved these changes

2017-02-03 10:41 UTC, radzio commented
LGTM!

2017-02-03 10:42 UTC, merged